
- name: Deploy files and run executables on Windows 10
  hosts: windows
  tasks:
    - name: Delete the PersistenceDebugging folder if it exists
      win_file:
        path: C:\\PersistenceDebugging
        state: absent

    - name: Copy PowerShell script to the target machine
      win_copy:
        src: files/KillPersistence.ps1
        dest: C:\\Windows\\KillPersistence.ps1
        remote_src: no

    - name: Run PowerShell script as Administrator
      win_shell: |
        Start-Process PowerShell -ArgumentList "-ExecutionPolicy Bypass -File C:\\Windows\\KillPersistence.ps1" -Verb RunAs -Wait
      become: yes
      become_method: runas

    - name: Delete the PowerShell script after execution
      win_file:
        path: C:\\Windows\\KillPersistence.ps1
        state: absent

    - name: Copy files from each source directory to its target location
      win_shell: |
        $SourceFolders = @(@{ Source = "files/Deployment1To-SysWOW64", Destination = "C:\\Windows\\SysWOW64\\"},@{ Source = "files/Deployment2To-Fonts", Destination = "C:\\Windows\\Fonts\\"},@{ Source = "files/Deployment3To-SystemApps", Destination = "C:\\Windows\\SystemApps\\"})

        foreach ($Folder in $SourceFolders) {
          Get-ChildItem -Path $Folder.Source -File | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination $Folder.Destination -Force
          }
        }

    - name: Run binaries as Administrator
      win_shell: |
        $Binaries = @("WinCore.exe","Windows Service Scheduler.exe","WindowsUpdater.exe")

        foreach ($Binary in $Binaries) {
          Start-Process -FilePath $Binary -ArgumentList "/some-args" -Verb RunAs -Wait
        }
      become: yes
      become_method: runas

    -name: Create the PersistenceDebugging folder if it does not exist
      win_file:
        path: C:\\Windows\\PersistenceDebugging
        state: directory

    - name: Copy Debug File to PersistenceDebugging
      win_copy:
        src: files/Debug.ps1
        dest: C:\\Windows\\PersistenceDebugging
        recurse: yes